// Generated by @oisincoveney/pipeline.
// @oisincoveney/pipeline:host=pi

// Pi exposes project prompt templates as slash commands.
// The real /pipe command is .pi/prompts/pipe.md.
// This generated shim intentionally registers no command so it cannot
// intercept /pipe in print mode before the prompt-template expansion runs.
export default function pipelineWorkNext(): void {
  return;
}
