// Generated by @oisincoveney/pipeline.
// @oisincoveney/pipeline:host=pi

interface PiCommand {
  name: string;
}
interface PiCommandContext {
  sendUserMessage(message: string): Promise<void> | void;
  ui: { notify(message: string, type?: string): void };
}
interface PiExtensionApi {
  getCommands?(): PiCommand[];
  registerCommand(
    name: string,
    command: {
      description: string;
      handler(args: string, ctx: PiCommandContext): Promise<void> | void;
    }
  ): void;
}

const WORKFLOW_NODES = [
  {
    agent: "pipeline-researcher",
    id: "research",
    kind: "agent",
    needs: [],
  },
  {
    agent: "pipeline-test-writer",
    id: "red",
    kind: "agent",
    needs: ["research"],
  },
  {
    agent: "pipeline-code-writer",
    id: "green",
    kind: "agent",
    needs: ["red"],
  },
  {
    agent: "pipeline-verifier",
    id: "verify",
    kind: "agent",
    needs: ["green"],
  },
  {
    agent: "pipeline-learner",
    id: "learn",
    kind: "agent",
    needs: ["verify"],
  },
] as const;

function renderSubagentCommand(task: string): string {
  const chain = WORKFLOW_NODES.filter((node) => node.kind === "agent")
    .map((node) => `${String(node.agent)}: ${node.id} ${task}`)
    .join(" -> ");
  return `/chain ${JSON.stringify(chain)}`;
}

export default function pipelineWorkNext(pi: PiExtensionApi): void {
  pi.registerCommand("pipe", {
    description: "Run the configured pipeline with Pi subagents",
    handler: async (args: string, ctx) => {
      const task = String(args ?? "").trim();
      if (!task) {
        ctx.ui.notify("Usage: /pipe <task description>", "error");
        return;
      }
      const commands =
        typeof pi.getCommands === "function" ? pi.getCommands() : [];
      const hasPiSubagents = commands.some((command) =>
        ["run", "chain", "parallel", "run-chain", "subagents-doctor"].some(
          (name) => command.name === name || command.name.startsWith(`${name}:`)
        )
      );
      if (!hasPiSubagents) {
        ctx.ui.notify("Install pi-subagents before running /pipe.", "error");
        return;
      }
      await ctx.sendUserMessage(renderSubagentCommand(task));
    },
  });
}
