// Generated by @oisincoveney/pipeline.
// @oisincoveney/pipeline:host=pi

interface PiCommand {
  name: string;
}

interface PiCommandContext {
  sendUserMessage(message: string): Promise<void> | void;
  ui: {
    notify(
      message: string,
      type?: "error" | "info" | "success" | "warning"
    ): void;
  };
}

interface PiExtensionApi {
  getCommands?(): PiCommand[];
  registerCommand(
    name: string,
    command: {
      description: string;
      handler(args: string, ctx: PiCommandContext): Promise<void> | void;
    }
  ): void;
}

const CHAIN_TASKS = {
  green: [
    "GREEN/code-write phase for the oisin pipeline.",
    "Use the previous RED output as context.",
    "Implement production code only until the failing tests pass.",
    "Run the targeted tests and typecheck.",
    "Return concrete evidence for the GREEN gate.",
  ].join("\n"),
  red: [
    "RED/test-write phase for the oisin pipeline.",
    "Use the previous research output as context.",
    "Add focused failing tests for the requested behavior only.",
    "Do not change production code.",
    "Run the targeted tests and return concrete failure evidence.",
  ].join("\n"),
  research: [
    "Research phase for the oisin pipeline.",
    "Build or read `.pipeline/knowledge-context.md` from repository rules and recent knowledge.",
    "Research the requested task, relevant files, existing patterns, and risks.",
    "Write `.pipeline/research.json`.",
    "Task: {task}",
  ].join("\n"),
  verify: [
    "VERIFY and LEARN phases for the oisin pipeline.",
    "Use the previous GREEN output as context.",
    "Run repository quality checks and review implementation fit.",
    "Write `.pipeline/knowledge/<timestamp>.md` with useful durable findings.",
    "Return PASS/FAIL with concrete evidence.",
  ].join("\n"),
} as const;

const quote = (value: string): string => JSON.stringify(value);

const renderSubagentCommand = (task: string): string =>
  [
    "/chain researcher ",
    quote(CHAIN_TASKS.research.replace("{task}", task)),
    " -> worker ",
    quote(CHAIN_TASKS.red),
    " -> worker ",
    quote(CHAIN_TASKS.green),
    " -> reviewer ",
    quote(CHAIN_TASKS.verify),
  ].join("");

export default function pipelineWorkNext(pi: PiExtensionApi): void {
  pi.registerCommand("work-next", {
    description: "Run the oisin pipeline with Pi subagents",
    handler: async (args: string, ctx) => {
      const task = String(args ?? "").trim();
      if (!task) {
        ctx.ui.notify(
          "Usage: /work-next <ticket id or task description>",
          "error"
        );
        return;
      }

      const commands =
        typeof pi.getCommands === "function" ? pi.getCommands() : [];
      const hasPiSubagents = commands.some((command) =>
        ["run", "chain", "parallel", "run-chain", "subagents-doctor"].some(
          (name) =>
            command.name === name ||
            command.name.startsWith([name, ""].join(":"))
        )
      );

      if (!hasPiSubagents) {
        ctx.ui.notify(
          "Install pi-subagents before running /work-next.",
          "error"
        );
        return;
      }

      await ctx.sendUserMessage(renderSubagentCommand(task));
    },
  });
}
