import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { installCommands, parseCommandHost } from "../src/install-commands.js";

const CODEX_SKILL_FRONTMATTER_RE =
  /^---\n[\s\S]*?name: work-next\n---\n<!-- Generated by @oisincoveney\/pipeline\. -->/;
const COMMAND_FRONTMATTER_RE =
  /^---\n[\s\S]*?description: [\s\S]*?\n---\n<!-- Generated by @oisincoveney\/pipeline\. -->/;

describe("installCommands", () => {
  let dir: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), "pipeline-commands-"));
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it("installs all host command adapters", async () => {
    const result = await installCommands({ cwd: dir, host: "all" });

    expect(result.items.every((item) => item.action === "create")).toBe(true);
    expect(result.items.map((item) => item.path)).toEqual([
      ".claude/commands/work-next.md",
      ".claude/agents/pipeline-researcher.md",
      ".claude/agents/pipeline-test-writer.md",
      ".claude/agents/pipeline-code-writer.md",
      ".claude/agents/pipeline-verifier.md",
      ".opencode/commands/work-next.md",
      ".opencode/agents/pipeline-orchestrator.md",
      ".opencode/agents/pipeline-researcher.md",
      ".opencode/agents/pipeline-test-writer.md",
      ".opencode/agents/pipeline-code-writer.md",
      ".opencode/agents/pipeline-verifier.md",
      ".agents/skills/work-next/SKILL.md",
      ".codex/agents/pipeline-researcher.toml",
      ".codex/agents/pipeline-test-writer.toml",
      ".codex/agents/pipeline-code-writer.toml",
      ".codex/agents/pipeline-verifier.toml",
      ".pi/prompts/work-next.md",
      ".pi/extensions/work-next.ts",
    ]);
    for (const item of result.items) {
      expect(existsSync(join(dir, item.path))).toBe(true);
    }
    expect(
      readFileSync(join(dir, ".claude/commands/work-next.md"), "utf8")
    ).toContain("Generated by @oisincoveney/pipeline");
    expect(
      readFileSync(join(dir, ".agents/skills/work-next/SKILL.md"), "utf8")
    ).toMatch(CODEX_SKILL_FRONTMATTER_RE);
    expect(
      readFileSync(join(dir, ".claude/commands/work-next.md"), "utf8")
    ).toMatch(COMMAND_FRONTMATTER_RE);
    expect(
      readFileSync(join(dir, ".opencode/commands/work-next.md"), "utf8")
    ).toMatch(COMMAND_FRONTMATTER_RE);
    expect(readFileSync(join(dir, ".pi/prompts/work-next.md"), "utf8")).toMatch(
      COMMAND_FRONTMATTER_RE
    );
    for (const item of result.items) {
      const content = readFileSync(join(dir, item.path), "utf8");
      if (item.path.endsWith(".ts")) {
        expect(content).toContain(
          `// @oisincoveney/pipeline:host=${item.host}`
        );
      } else if (!item.path.endsWith(".toml")) {
        expect(content).toContain(
          `<!-- @oisincoveney/pipeline:host=${item.host} -->`
        );
      }
      expect(content).not.toContain("version=");
    }
  });

  it("generates host resources that configure native agents instead of shelling to the CLI", async () => {
    await installCommands({ cwd: dir, host: "all" });

    const claudeCommand = readFileSync(
      join(dir, ".claude/commands/work-next.md"),
      "utf8"
    );
    const opencodeCommand = readFileSync(
      join(dir, ".opencode/commands/work-next.md"),
      "utf8"
    );
    const codexSkill = readFileSync(
      join(dir, ".agents/skills/work-next/SKILL.md"),
      "utf8"
    );
    const piExtension = readFileSync(
      join(dir, ".pi/extensions/work-next.ts"),
      "utf8"
    );

    expect(claudeCommand).toContain("pipeline-researcher");
    expect(opencodeCommand).toContain("agent: pipeline-orchestrator");
    expect(opencodeCommand).toContain("subtask: true");
    expect(codexSkill).toContain("$work-next <ticket id or task description>");
    expect(piExtension).toContain("export default function pipelineWorkNext");
    expect(piExtension).toContain('pi.registerCommand("work-next", {');
    expect(piExtension).toContain('"/chain researcher "');
    expect(piExtension).toContain('" -> worker "');
    expect(piExtension).toContain('" -> reviewer "');
    expect(piExtension).toContain('"run-chain"');
    expect(piExtension).not.toContain("sendUserMessage(renderWorkflowPrompt");

    for (const content of [
      claudeCommand,
      opencodeCommand,
      codexSkill,
      piExtension,
    ]) {
      expect(content).not.toContain("bunx @oisincoveney/pipeline");
      expect(content).not.toContain("./node_modules/.bin/work-next");
    }
  });

  it("generates discoverable agent configuration for each agent host", async () => {
    await installCommands({ cwd: dir, host: "all" });

    expect(
      readFileSync(join(dir, ".claude/agents/pipeline-researcher.md"), "utf8")
    ).toContain("name: pipeline-researcher");
    expect(
      readFileSync(
        join(dir, ".opencode/agents/pipeline-orchestrator.md"),
        "utf8"
      )
    ).toContain("mode: primary");
    expect(
      readFileSync(join(dir, ".opencode/agents/pipeline-researcher.md"), "utf8")
    ).toContain("mode: subagent");
    expect(
      readFileSync(join(dir, ".codex/agents/pipeline-researcher.toml"), "utf8")
    ).toContain('name = "pipeline-researcher"');
  });

  it("is idempotent and check passes after install", async () => {
    await installCommands({ cwd: dir, host: "all" });

    const second = await installCommands({ cwd: dir, host: "all" });
    const checked = await installCommands({
      check: true,
      cwd: dir,
      host: "all",
    });

    expect(second.items.every((item) => item.action === "unchanged")).toBe(
      true
    );
    expect(checked.items.every((item) => item.action === "unchanged")).toBe(
      true
    );
  });

  it("dry-run reports creates without writing files", async () => {
    const result = await installCommands({
      cwd: dir,
      dryRun: true,
      host: "claude",
    });

    expect(result.items.every((item) => item.action === "create")).toBe(true);
    expect(result.items.every((item) => item.host === "claude")).toBe(true);
    expect(existsSync(join(dir, ".claude/commands/work-next.md"))).toBe(false);
  });

  it("dry-run reports conflicts without throwing or overwriting", async () => {
    const path = join(dir, ".claude/commands/work-next.md");
    mkdirSync(join(dir, ".claude/commands"), { recursive: true });
    writeFileSync(path, "manual command");

    const result = await installCommands({
      cwd: dir,
      dryRun: true,
      host: "claude",
    });

    expect(result.items[0]).toMatchObject({
      action: "conflict",
      host: "claude",
      path: ".claude/commands/work-next.md",
    });
    expect(readFileSync(path, "utf8")).toBe("manual command");
  });

  it("check fails when commands are missing", async () => {
    await expect(
      installCommands({ check: true, cwd: dir, host: "claude" })
    ).rejects.toThrow("not up to date");
  });

  it("refuses to overwrite manually edited files unless forced", async () => {
    const path = join(dir, ".claude/commands/work-next.md");
    mkdirSync(join(dir, ".claude/commands"), { recursive: true });
    writeFileSync(path, "manual command");

    await expect(installCommands({ cwd: dir, host: "claude" })).rejects.toThrow(
      "Refusing to overwrite"
    );

    const forced = await installCommands({
      cwd: dir,
      force: true,
      host: "claude",
    });

    expect(forced.items[0]).toMatchObject({
      action: "update",
      host: "claude",
      path: ".claude/commands/work-next.md",
    });
    expect(readFileSync(path, "utf8")).toContain(
      "Generated by @oisincoveney/pipeline"
    );
  });

  it("validates host names through Commander parser hook", () => {
    expect(parseCommandHost("all")).toBe("all");
    expect(parseCommandHost("pi")).toBe("pi");
    expect(() => parseCommandHost("bad")).toThrow('Unsupported host "bad"');
  });
});
