import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { installCommands, parseCommandHost } from "../src/install-commands.js";
import { initPipelineProject } from "../src/pipeline-init.js";

const CODEX_SKILL_FRONTMATTER_RE =
  /^---\n[\s\S]*?name: pipe\n---\n<!-- Generated by @oisincoveney\/pipeline\. -->/;
const COMMAND_FRONTMATTER_RE =
  /^---\n[\s\S]*?description: [\s\S]*?\n---\n<!-- Generated by @oisincoveney\/pipeline\. -->/;

describe("installCommands", () => {
  let dir: string;

  beforeEach(async () => {
    dir = mkdtempSync(join(tmpdir(), "pipeline-commands-"));
    await initPipelineProject({ cwd: dir });
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it("installs all host command adapters", async () => {
    const result = await installCommands({ cwd: dir, host: "all" });

    expect(result.items.every((item) => item.action === "create")).toBe(true);
    expect(result.items.map((item) => item.path)).toEqual([
      ".claude/commands/pipe.md",
      ".opencode/commands/pipe.md",
      ".opencode/agents/pipeline-orchestrator.md",
      ".agents/skills/pipe/SKILL.md",
      ".codex/agents/pipeline-code-writer.toml",
      ".codex/agents/pipeline-inspector.toml",
      ".codex/agents/pipeline-learner.toml",
      ".codex/agents/pipeline-researcher.toml",
      ".codex/agents/pipeline-test-writer.toml",
      ".codex/agents/pipeline-verifier.toml",
      ".kimi/skills/pipe/SKILL.md",
      ".pi/prompts/pipe.md",
    ]);
    for (const item of result.items) {
      expect(existsSync(join(dir, item.path))).toBe(true);
    }
    expect(
      readFileSync(join(dir, ".claude/commands/pipe.md"), "utf8")
    ).toContain("Generated by @oisincoveney/pipeline");
    expect(
      readFileSync(join(dir, ".agents/skills/pipe/SKILL.md"), "utf8")
    ).toMatch(CODEX_SKILL_FRONTMATTER_RE);
    expect(readFileSync(join(dir, ".claude/commands/pipe.md"), "utf8")).toMatch(
      COMMAND_FRONTMATTER_RE
    );
    expect(
      readFileSync(join(dir, ".opencode/commands/pipe.md"), "utf8")
    ).toMatch(COMMAND_FRONTMATTER_RE);
    expect(readFileSync(join(dir, ".pi/prompts/pipe.md"), "utf8")).toMatch(
      COMMAND_FRONTMATTER_RE
    );
    for (const item of result.items) {
      const content = readFileSync(join(dir, item.path), "utf8");
      if (item.path.endsWith(".ts")) {
        expect(content).toContain(
          `// @oisincoveney/pipeline:host=${item.host}`
        );
      } else if (item.path.endsWith(".yaml")) {
        expect(content).toContain(`# @oisincoveney/pipeline:host=${item.host}`);
      } else if (!item.path.endsWith(".toml")) {
        expect(content).toContain(
          `<!-- @oisincoveney/pipeline:host=${item.host} -->`
        );
      }
      expect(content).not.toContain("version=");
    }
  });

  it("generates host resources with runner-aware dispatch instructions", async () => {
    await installCommands({ cwd: dir, host: "all" });

    const claudeCommand = readFileSync(
      join(dir, ".claude/commands/pipe.md"),
      "utf8"
    );
    const opencodeCommand = readFileSync(
      join(dir, ".opencode/commands/pipe.md"),
      "utf8"
    );
    const opencodeOrchestrator = readFileSync(
      join(dir, ".opencode/agents/pipeline-orchestrator.md"),
      "utf8"
    );
    const codexSkill = readFileSync(
      join(dir, ".agents/skills/pipe/SKILL.md"),
      "utf8"
    );
    const piPrompt = readFileSync(join(dir, ".pi/prompts/pipe.md"), "utf8");

    expect(claudeCommand).toContain("pipeline-researcher");
    expect(opencodeCommand).toContain("agent: pipeline-orchestrator");
    expect(opencodeCommand).not.toContain("subtask: true");
    expect(opencodeOrchestrator).toContain("task: deny");
    expect(opencodeOrchestrator).toContain(
      "red: codex CLI profile=pipeline-test-writer"
    );
    expect(codexSkill).toContain("$pipe <task description>");
    expect(codexSkill).toContain(
      "green: spawn_agent agent_type=pipeline-code-writer runner=codex needs=red"
    );
    expect(codexSkill).not.toContain("agent_type=worker");
    expect(existsSync(join(dir, ".pi/extensions/pipe.ts"))).toBe(false);
    expect(piPrompt).toContain("pipeline-researcher");
    expect(piPrompt).toContain("pipeline-test-writer");
    expect(piPrompt).toContain("Pi native dispatch is not enabled");
    expect(piPrompt).not.toContain("Pi native subagent");

    for (const content of [
      claudeCommand,
      opencodeCommand,
      opencodeOrchestrator,
      codexSkill,
      piPrompt,
    ]) {
      expect(content).toContain("Do not use `pipe`, `oisin-pipeline`");
      expect(content).not.toContain("For lines marked");
      expect(content).not.toContain("CLI dispatch command shapes");
      expect(content).not.toContain("instruction-only translation");
      expect(content).not.toContain("bunx @oisincoveney/pipeline");
      expect(content).not.toContain("./node_modules/.bin/pipe");
    }
  });

  it("generates discoverable agent configuration for each agent host", async () => {
    await installCommands({ cwd: dir, host: "all" });

    expect(
      readFileSync(
        join(dir, ".opencode/agents/pipeline-orchestrator.md"),
        "utf8"
      )
    ).toContain("mode: primary");
    expect(
      readFileSync(join(dir, ".codex/agents/pipeline-researcher.toml"), "utf8")
    ).toContain('name = "pipeline-researcher"');
    expect(existsSync(join(dir, ".claude/agents/pipeline-researcher.md"))).toBe(
      false
    );
    expect(
      existsSync(join(dir, ".opencode/agents/pipeline-researcher.md"))
    ).toBe(false);
    expect(existsSync(join(dir, ".kimi/agents/pipeline-researcher.yaml"))).toBe(
      false
    );
  });

  it("generates Kimi native agents as YAML specs", async () => {
    const configPath = join(dir, ".pipeline/profiles.yaml");
    const config = readFileSync(configPath, "utf8").replace(
      "  pipeline-code-writer:\n    runner: codex",
      "  pipeline-code-writer:\n    runner: kimi"
    );
    writeFileSync(configPath, config);

    await installCommands({ cwd: dir, host: "kimi" });

    const agent = readFileSync(
      join(dir, ".kimi/agents/pipeline-code-writer.yaml"),
      "utf8"
    );
    expect(agent).toContain("# @oisincoveney/pipeline:host=kimi");
    expect(agent).toContain("version: 1");
    expect(agent).toContain("name: pipeline-code-writer");
    expect(agent).toContain("extend: default");
    expect(agent).toContain(
      "system_prompt_path: ../../.pipeline/prompts/code-writer.md"
    );

    const checked = await installCommands({
      check: true,
      cwd: dir,
      host: "kimi",
    });
    expect(checked.items.every((item) => item.action === "unchanged")).toBe(
      true
    );
  });

  it("deletes obsolete generated host resources", async () => {
    await installCommands({ cwd: dir, host: "all" });
    const obsoleteKimiCommand = join(dir, ".kimi/commands/pipe.md");
    const obsoleteClaudeAgent = join(dir, ".claude/agents/old.md");
    mkdirSync(join(dir, ".kimi/commands"), { recursive: true });
    mkdirSync(join(dir, ".claude/agents"), { recursive: true });
    writeFileSync(
      obsoleteKimiCommand,
      [
        "<!-- Generated by @oisincoveney/pipeline. -->",
        "<!-- @oisincoveney/pipeline:host=kimi -->",
        "",
      ].join("\n")
    );
    writeFileSync(
      obsoleteClaudeAgent,
      [
        "<!-- Generated by @oisincoveney/pipeline. -->",
        "<!-- @oisincoveney/pipeline:host=claude -->",
        "",
      ].join("\n")
    );

    await expect(
      installCommands({
        check: true,
        cwd: dir,
        host: "all",
      })
    ).rejects.toThrow(".kimi/commands/pipe.md: delete");

    const dryRun = await installCommands({
      cwd: dir,
      dryRun: true,
      host: "all",
    });
    expect(dryRun.items).toContainEqual(
      expect.objectContaining({
        action: "delete",
        host: "kimi",
        path: ".kimi/commands/pipe.md",
      })
    );

    const result = await installCommands({ cwd: dir, host: "all" });
    expect(result.items).toContainEqual(
      expect.objectContaining({
        action: "delete",
        host: "claude",
        path: ".claude/agents/old.md",
      })
    );
    expect(existsSync(obsoleteKimiCommand)).toBe(false);
    expect(existsSync(obsoleteClaudeAgent)).toBe(false);
  });

  it("uses canonical runner models for OpenCode native mixed-runner subagents", async () => {
    const runnersPath = join(dir, ".pipeline/runners.yaml");
    const runners = readFileSync(runnersPath, "utf8")
      .replace(
        "  codex:\n    type: codex",
        "  codex:\n    type: codex\n    model: openai/gpt-5.3-codex"
      )
      .replace(
        "  kimi:\n    type: kimi",
        "  kimi:\n    type: kimi\n    model: moonshot/kimi-k2.6"
      );
    writeFileSync(runnersPath, runners);

    const profilesPath = join(dir, ".pipeline/profiles.yaml");
    const profiles = readFileSync(profilesPath, "utf8").replace(
      "  pipeline-code-writer:\n    runner: codex",
      "  pipeline-code-writer:\n    runner: kimi"
    );
    writeFileSync(profilesPath, profiles);

    await installCommands({ cwd: dir, host: "opencode" });

    const testWriter = readFileSync(
      join(dir, ".opencode/agents/pipeline-test-writer.md"),
      "utf8"
    );
    const codeWriter = readFileSync(
      join(dir, ".opencode/agents/pipeline-code-writer.md"),
      "utf8"
    );
    expect(testWriter).toContain("model: openai/gpt-5.3-codex");
    expect(codeWriter).toContain("model: moonshot/kimi-k2.6");
    expect(
      readFileSync(join(dir, ".opencode/commands/pipe.md"), "utf8")
    ).toContain(
      "green: Task tool subagent_type=pipeline-code-writer model=moonshot/kimi-k2.6 runner=kimi needs=red"
    );
  });

  it("uses Kimi native Agent subagents when the orchestrator spec is loaded", async () => {
    const configPath = join(dir, ".pipeline/profiles.yaml");
    const config = readFileSync(configPath, "utf8").replace(
      "  pipeline-code-writer:\n    runner: codex",
      "  pipeline-code-writer:\n    runner: kimi"
    );
    writeFileSync(configPath, config);

    await installCommands({ cwd: dir, host: "kimi" });

    const command = readFileSync(
      join(dir, ".kimi/skills/pipe/SKILL.md"),
      "utf8"
    );
    const orchestrator = readFileSync(
      join(dir, ".kimi/agents/pipeline-orchestrator.yaml"),
      "utf8"
    );
    expect(command).toContain("name: pipe");
    expect(command).toContain(
      "green: Agent tool subagent_type=pipeline-code-writer runner=kimi needs=red"
    );
    expect(command).toContain("Do not claim CLI routes are Kimi native routes");
    expect(orchestrator).toContain("name: pipeline-orchestrator");
    expect(orchestrator).toContain("kimi_cli.tools.agent:Agent");
    expect(orchestrator).toContain("pipeline-code-writer:");
    expect(orchestrator).toContain("path: ./pipeline-code-writer.yaml");
  });

  it("projects every orchestrator host against every runner without fake native dispatch", async () => {
    writeFileSync(
      join(dir, ".pipeline/pipeline.yaml"),
      `
version: 1
default_workflow: all-runners
orchestrator:
  profile: orchestrator
workflows:
  all-runners:
    nodes:
      - id: codex-node
        kind: agent
        profile: codex-agent
      - id: claude-node
        kind: agent
        profile: claude-agent
      - id: opencode-node
        kind: agent
        profile: opencode-agent
      - id: kimi-node
        kind: agent
        profile: kimi-agent
      - id: pi-node
        kind: agent
        profile: pi-agent
`.trimStart()
    );
    writeFileSync(
      join(dir, ".pipeline/runners.yaml"),
      `
version: 1
runners:
  codex:
    type: codex
    command: codex
    model: openai/gpt-5.3-codex
    capabilities: &agent_caps
      native_subagents: true
      rules: true
      skills: false
      mcp_servers: false
      tools: [read, list, grep, glob, bash, edit, write, task]
      filesystem: [read-only, workspace-write]
      network: [inherit]
      output_formats: [text, json]
  claude:
    type: claude
    command: claude
    model: anthropic/claude-sonnet-4-6
    capabilities: *agent_caps
  opencode:
    type: opencode
    command: opencode
    model: openai/gpt-5.4-mini
    capabilities: *agent_caps
  kimi:
    type: kimi
    command: kimi
    model: kimi-for-coding/k2p6
    capabilities: *agent_caps
  pi:
    type: pi
    command: pi
    model: openai/gpt-5.4-mini
    capabilities: *agent_caps
`.trimStart()
    );
    writeFileSync(
      join(dir, ".pipeline/profiles.yaml"),
      `
version: 1
profiles:
  orchestrator:
    runner: codex
    instructions: { inline: Orchestrate. }
  codex-agent:
    runner: codex
    instructions: { inline: Codex. }
  claude-agent:
    runner: claude
    instructions: { inline: Claude. }
  opencode-agent:
    runner: opencode
    instructions: { inline: OpenCode. }
  kimi-agent:
    runner: kimi
    instructions: { inline: Kimi. }
  pi-agent:
    runner: pi
    instructions: { inline: Pi. }
`.trimStart()
    );

    await installCommands({ cwd: dir, force: true, host: "all" });

    const codex = readFileSync(
      join(dir, ".agents/skills/pipe/SKILL.md"),
      "utf8"
    );
    expect(codex).toContain(
      "codex-node: spawn_agent agent_type=codex-agent runner=codex needs=none"
    );
    expect(codex).toContain("claude-node: claude CLI profile=claude-agent");
    expect(codex).toContain(
      "Do not substitute the generic Codex worker for configured profiles"
    );

    const claude = readFileSync(join(dir, ".claude/commands/pipe.md"), "utf8");
    expect(claude).toContain(
      "claude-node: Agent tool subagent_type=claude-agent runner=claude needs=none"
    );
    expect(claude).toContain("kimi-node: kimi CLI profile=kimi-agent");

    const opencode = readFileSync(
      join(dir, ".opencode/commands/pipe.md"),
      "utf8"
    );
    expect(opencode).toContain(
      "codex-node: Task tool subagent_type=codex-agent model=openai/gpt-5.3-codex runner=codex needs=none"
    );
    expect(opencode).toContain(
      "claude-node: Task tool subagent_type=claude-agent model=anthropic/claude-sonnet-4-6 runner=claude needs=none"
    );
    expect(opencode).toContain(
      "opencode-node: Task tool subagent_type=opencode-agent runner=opencode needs=none"
    );
    expect(opencode).toContain(
      "kimi-node: Task tool subagent_type=kimi-agent model=kimi-for-coding/k2p6 runner=kimi needs=none"
    );
    expect(opencode).toContain(
      "pi-node: Task tool subagent_type=pi-agent model=openai/gpt-5.4-mini runner=pi needs=none"
    );

    const kimi = readFileSync(join(dir, ".kimi/skills/pipe/SKILL.md"), "utf8");
    expect(kimi).toContain(
      "kimi-node: Agent tool subagent_type=kimi-agent runner=kimi needs=none"
    );
    expect(kimi).toContain("codex-node: codex CLI profile=codex-agent");
    expect(
      readFileSync(join(dir, ".kimi/agents/pipeline-orchestrator.yaml"), "utf8")
    ).toContain("kimi-agent:");
    expect(existsSync(join(dir, ".kimi/agents/kimi-agent.yaml"))).toBe(true);

    const pi = readFileSync(join(dir, ".pi/prompts/pipe.md"), "utf8");
    expect(pi).toContain("pi-node: pi CLI profile=pi-agent");
    expect(pi).toContain("codex-node: codex CLI profile=codex-agent");
    expect(pi).not.toContain("Pi native subagent");
  });

  it("projects configured orchestrator grants into every host surface", async () => {
    mkdirSync(join(dir, ".agents/skills/orchestrator"), { recursive: true });
    writeFileSync(
      join(dir, ".agents/skills/orchestrator/SKILL.md"),
      "# Orchestrator skill\n"
    );
    const configPath = join(dir, ".pipeline/profiles.yaml");
    const config = readFileSync(configPath, "utf8")
      .replace(
        "skills: {}",
        "skills:\n  orchestrator:\n    path: .agents/skills/orchestrator/SKILL.md"
      )
      .replace(
        "mcp_servers: {}",
        "mcp_servers:\n  knowledge-base:\n    command: node\n    args: [kb.js]"
      )
      .replace(
        "  orchestrator:\n    runner: codex",
        "  orchestrator:\n    runner: codex\n    model: gpt-5-orchestrator"
      )
      .replace(
        "    tools: [read, list, grep, glob, bash]",
        "    skills: [orchestrator]\n    mcp_servers: [knowledge-base]\n    tools: [read, list, grep, glob, bash]"
      );
    writeFileSync(configPath, config);

    await installCommands({ cwd: dir, force: true, host: "all" });

    const surfaces = [
      ".claude/commands/pipe.md",
      ".opencode/commands/pipe.md",
      ".opencode/agents/pipeline-orchestrator.md",
      ".agents/skills/pipe/SKILL.md",
      ".kimi/skills/pipe/SKILL.md",
      ".pi/prompts/pipe.md",
    ].map((path) => readFileSync(join(dir, path), "utf8"));

    for (const content of surfaces) {
      expect(content).toContain("Configured orchestrator:");
      expect(content).toContain("model: gpt-5-orchestrator");
      expect(content).toContain("skills: orchestrator");
      expect(content).toContain("mcp_servers: knowledge-base");
    }
  });

  it("is idempotent and check passes after install", async () => {
    await installCommands({ cwd: dir, host: "all" });

    const second = await installCommands({ cwd: dir, host: "all" });
    const checked = await installCommands({
      check: true,
      cwd: dir,
      host: "all",
    });

    expect(second.items.every((item) => item.action === "unchanged")).toBe(
      true
    );
    expect(checked.items.every((item) => item.action === "unchanged")).toBe(
      true
    );
  });

  it("dry-run reports creates without writing files", async () => {
    const result = await installCommands({
      cwd: dir,
      dryRun: true,
      host: "claude",
    });

    expect(result.items.every((item) => item.action === "create")).toBe(true);
    expect(result.items.every((item) => item.host === "claude")).toBe(true);
    expect(existsSync(join(dir, ".claude/commands/pipe.md"))).toBe(false);
  });

  it("dry-run reports conflicts without throwing or overwriting", async () => {
    const path = join(dir, ".claude/commands/pipe.md");
    mkdirSync(join(dir, ".claude/commands"), { recursive: true });
    writeFileSync(path, "manual command");

    const result = await installCommands({
      cwd: dir,
      dryRun: true,
      host: "claude",
    });

    expect(result.items[0]).toMatchObject({
      action: "conflict",
      host: "claude",
      path: ".claude/commands/pipe.md",
    });
    expect(readFileSync(path, "utf8")).toBe("manual command");
  });

  it("check fails when commands are missing", async () => {
    await expect(
      installCommands({ check: true, cwd: dir, host: "claude" })
    ).rejects.toThrow("not up to date");
  });

  it("refuses to overwrite manually edited files unless forced", async () => {
    const path = join(dir, ".claude/commands/pipe.md");
    mkdirSync(join(dir, ".claude/commands"), { recursive: true });
    writeFileSync(path, "manual command");

    await expect(installCommands({ cwd: dir, host: "claude" })).rejects.toThrow(
      "Refusing to overwrite"
    );

    const forced = await installCommands({
      cwd: dir,
      force: true,
      host: "claude",
    });

    expect(forced.items[0]).toMatchObject({
      action: "update",
      host: "claude",
      path: ".claude/commands/pipe.md",
    });
    expect(readFileSync(path, "utf8")).toContain(
      "Generated by @oisincoveney/pipeline"
    );
  });

  it("validates host names through Commander parser hook", () => {
    expect(parseCommandHost("all")).toBe("all");
    expect(parseCommandHost("kimi")).toBe("kimi");
    expect(parseCommandHost("pi")).toBe("pi");
    expect(() => parseCommandHost("bad")).toThrow('Unsupported host "bad"');
  });
});
