import { existsSync, readFileSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import matter from "gray-matter";
import { stringify as stringifyToml } from "smol-toml";
import {
  PIPELINE_AGENTS,
  type PipelineSpecAgent,
  renderPipelineWorkflow,
} from "./pipeline-spec.js";

const GENERATED_MARKER = "<!-- Generated by @oisincoveney/pipeline. -->";
const GENERATED_TS_MARKER = "// Generated by @oisincoveney/pipeline.";
const OWNER_MARKER_PREFIX = "<!-- @oisincoveney/pipeline:";
const OWNER_TS_MARKER_PREFIX = "// @oisincoveney/pipeline:";

export const COMMAND_HOSTS = ["claude", "opencode", "codex", "pi"] as const;

export type CommandHost = (typeof COMMAND_HOSTS)[number];
export type CommandHostSelection = CommandHost | "all";
export type InstallAction = "conflict" | "create" | "unchanged" | "update";

export interface CommandInstallPlanItem {
  action: InstallAction;
  host: CommandHost;
  invocation: string;
  path: string;
}

export interface InstallCommandsOptions {
  check?: boolean;
  cwd?: string;
  dryRun?: boolean;
  force?: boolean;
  host?: CommandHostSelection;
}

export interface InstallCommandsResult {
  items: CommandInstallPlanItem[];
}

interface CommandDefinition {
  content: string;
  host: CommandHost;
  invocation: string;
  path: string;
}

function header(host: CommandHost): string {
  return [GENERATED_MARKER, `${OWNER_MARKER_PREFIX}host=${host} -->`, ""].join(
    "\n"
  );
}

function tsHeader(host: CommandHost): string {
  return [
    GENERATED_TS_MARKER,
    `${OWNER_TS_MARKER_PREFIX}host=${host}`,
    "",
  ].join("\n");
}

function markdown(data: Record<string, unknown>, body: string): string {
  return `${matter.stringify(body.trimEnd(), data).trimEnd()}\n`;
}

function agentNames(): string {
  return PIPELINE_AGENTS.map((agent) => `\`${agent.name}\``).join(", ");
}

function claudeTools(agent: PipelineSpecAgent): string {
  const toolNames = new Set<string>();
  for (const tool of agent.tools) {
    switch (tool) {
      case "bash":
        toolNames.add("Bash");
        break;
      case "edit":
        toolNames.add("Edit");
        break;
      case "glob":
        toolNames.add("Glob");
        break;
      case "grep":
        toolNames.add("Grep");
        break;
      case "list":
        toolNames.add("LS");
        break;
      case "read":
        toolNames.add("Read");
        break;
      case "write":
        toolNames.add("Write");
        break;
      default:
        break;
    }
  }
  return [...toolNames].join(", ");
}

function claudeAgentDefinition(agent: PipelineSpecAgent): CommandDefinition {
  return {
    content: markdown(
      {
        description: agent.description,
        name: agent.name,
        tools: claudeTools(agent),
      },
      [
        header("claude").trimEnd(),
        "",
        agent.description,
        "",
        "Follow the oisin pipeline phase contract. Keep changes scoped to your assigned role and return concrete evidence to the orchestrating `/pipe` command.",
        "",
      ].join("\n")
    ),
    host: "claude",
    invocation: "/pipe <ticket id or task description>",
    path: `.claude/agents/${agent.name}.md`,
  };
}

function claudeDefinitions(): CommandDefinition[] {
  const args = "$ARGUMENTS";
  return [
    {
      content: markdown(
        {
          "argument-hint": "<ticket id or task description>",
          description: "Run the oisin pipeline with Claude Code project agents",
        },
        [
          header("claude").trimEnd(),
          "",
          renderPipelineWorkflow(args),
          "",
          "Claude execution contract:",
          `- Delegate phase work to project agents: ${agentNames()}.`,
          "- Use the researcher for research, test-writer for RED, code-writer for GREEN, and verifier for VERIFY.",
          "- Keep the command session as the orchestrator that enforces phase order and gates.",
          "",
        ].join("\n")
      ),
      host: "claude",
      invocation: "/pipe <ticket id or task description>",
      path: ".claude/commands/pipe.md",
    },
    ...PIPELINE_AGENTS.map(claudeAgentDefinition),
  ];
}

function opencodePermission(agent: PipelineSpecAgent): Record<string, string> {
  return {
    bash: agent.tools.includes("bash") ? "allow" : "deny",
    edit: agent.tools.includes("edit") ? "allow" : "deny",
    glob: "allow",
    grep: "allow",
    list: "allow",
    read: "allow",
    task: "deny",
    write: agent.tools.includes("write") ? "allow" : "deny",
  };
}

function opencodeAgentDefinition(
  agent: PipelineSpecAgent,
  mode: "primary" | "subagent"
): CommandDefinition {
  const permission =
    mode === "primary"
      ? {
          bash: "allow",
          edit: "allow",
          glob: "allow",
          grep: "allow",
          list: "allow",
          read: "allow",
          task: "allow",
          write: "allow",
        }
      : opencodePermission(agent);

  return {
    content: markdown(
      {
        description: agent.description,
        mode,
        permission,
      },
      [
        header("opencode").trimEnd(),
        "",
        agent.description,
        "",
        mode === "primary"
          ? `Orchestrate the oisin pipeline and delegate phase work to ${agentNames()} with the Task tool.`
          : "Follow the oisin pipeline phase contract for your assigned role and return concrete evidence to the orchestrator.",
        "",
      ].join("\n")
    ),
    host: "opencode",
    invocation: "/pipe <ticket id or task description>",
    path: `.opencode/agents/${agent.name}.md`,
  };
}

function opencodeDefinitions(): CommandDefinition[] {
  const args = "$ARGUMENTS";
  const orchestrator: PipelineSpecAgent = {
    description:
      "Orchestrate the oisin pipeline, delegate phase work to OpenCode subagents, and enforce gates.",
    name: "pipeline-orchestrator",
    role: "verifier",
    tools: ["read", "grep", "glob", "list", "edit", "write", "bash"],
  };

  return [
    {
      content: markdown(
        {
          agent: "pipeline-orchestrator",
          description: "Run the oisin pipeline with OpenCode subagents",
          subtask: true,
        },
        [
          header("opencode").trimEnd(),
          "",
          renderPipelineWorkflow(args),
          "",
          "OpenCode execution contract:",
          "- Run as `pipeline-orchestrator`.",
          `- Delegate phase work to subagents: ${agentNames()}.`,
          "- Enforce phase order and gates in the command session.",
          "",
        ].join("\n")
      ),
      host: "opencode",
      invocation: "/pipe <ticket id or task description>",
      path: ".opencode/commands/pipe.md",
    },
    opencodeAgentDefinition(orchestrator, "primary"),
    ...PIPELINE_AGENTS.map((agent) =>
      opencodeAgentDefinition(agent, "subagent")
    ),
  ];
}

function piChainTasks(): Record<string, string> {
  return {
    green: [
      "GREEN/code-write phase for the oisin pipeline.",
      "Use the previous RED output as context.",
      "Implement production code only until the failing tests pass.",
      "Run the targeted tests and typecheck.",
      "Return concrete evidence for the GREEN gate.",
    ].join("\n"),
    red: [
      "RED/test-write phase for the oisin pipeline.",
      "Use the previous research output as context.",
      "Add focused failing tests for the requested behavior only.",
      "Do not change production code.",
      "Run the targeted tests and return concrete failure evidence.",
    ].join("\n"),
    research: [
      "Research phase for the oisin pipeline.",
      "Build or read `.pipeline/knowledge-context.md` from repository rules and recent knowledge.",
      "Research the requested task, relevant files, existing patterns, and risks.",
      "Write `.pipeline/research.json`.",
      "Task: {task}",
    ].join("\n"),
    verify: [
      "VERIFY and LEARN phases for the oisin pipeline.",
      "Use the previous GREEN output as context.",
      "Run repository quality checks and review implementation fit.",
      "Write `.pipeline/knowledge/<timestamp>.md` with useful durable findings.",
      "Return PASS/FAIL with concrete evidence.",
    ].join("\n"),
  };
}

function piDefinitions(): CommandDefinition[] {
  const args = "$ARGUMENTS";
  return [
    {
      content: markdown(
        {
          "argument-hint": "<ticket id or task description>",
          description: "Fallback prompt for the oisin pipeline",
        },
        [
          header("pi").trimEnd(),
          "",
          "This prompt is fallback documentation. The mechanical Pi path is `.pi/extensions/pipe.ts`.",
          "",
          renderPipelineWorkflow(args),
          "",
        ].join("\n")
      ),
      host: "pi",
      invocation: "/pipe <ticket id or task description>",
      path: ".pi/prompts/pipe.md",
    },
    {
      content: [
        tsHeader("pi").trimEnd(),
        "",
        "interface PiCommand {",
        "  name: string;",
        "}",
        "",
        "interface PiCommandContext {",
        "  sendUserMessage(message: string): Promise<void> | void;",
        "  ui: {",
        "    notify(",
        "      message: string,",
        '      type?: "error" | "info" | "success" | "warning"',
        "    ): void;",
        "  };",
        "}",
        "",
        "interface PiExtensionApi {",
        "  getCommands?(): PiCommand[];",
        "  registerCommand(",
        "    name: string,",
        "    command: {",
        "      description: string;",
        "      handler(args: string, ctx: PiCommandContext): Promise<void> | void;",
        "    }",
        "  ): void;",
        "}",
        "",
        "const CHAIN_TASKS = {",
        ...Object.entries(piChainTasks()).flatMap(([key, lines]) => [
          `  ${key}: [`,
          ...lines.split("\n").map((line) => `    ${JSON.stringify(line)},`),
          '  ].join("\\n"),',
        ]),
        "} as const;",
        "",
        "const quote = (value: string): string => JSON.stringify(value);",
        "",
        "const renderSubagentCommand = (task: string): string =>",
        "  [",
        '    "/chain researcher ",',
        '    quote(CHAIN_TASKS.research.replace("{task}", task)),',
        '    " -> worker ",',
        "    quote(CHAIN_TASKS.red),",
        '    " -> worker ",',
        "    quote(CHAIN_TASKS.green),",
        '    " -> reviewer ",',
        "    quote(CHAIN_TASKS.verify),",
        '  ].join("");',
        "",
        "export default function pipelineWorkNext(pi: PiExtensionApi): void {",
        '  pi.registerCommand("pipe", {',
        '    description: "Run the oisin pipeline with Pi subagents",',
        "    handler: async (args: string, ctx) => {",
        '      const task = String(args ?? "").trim();',
        "      if (!task) {",
        "        ctx.ui.notify(",
        '          "Usage: /pipe <ticket id or task description>",',
        '          "error"',
        "        );",
        "        return;",
        "      }",
        "",
        "      const commands =",
        '        typeof pi.getCommands === "function" ? pi.getCommands() : [];',
        "      const hasPiSubagents = commands.some((command) =>",
        '        ["run", "chain", "parallel", "run-chain", "subagents-doctor"].some(',
        "          (name) =>",
        "            command.name === name ||",
        '            command.name.startsWith([name, ""].join(":"))',
        "        )",
        "      );",
        "",
        "      if (!hasPiSubagents) {",
        "        ctx.ui.notify(",
        '          "Install pi-subagents before running /pipe.",',
        '          "error"',
        "        );",
        "        return;",
        "      }",
        "",
        "      await ctx.sendUserMessage(renderSubagentCommand(task));",
        "    },",
        "  });",
        "}",
        "",
      ].join("\n"),
      host: "pi",
      invocation: "/pipe <ticket id or task description>",
      path: ".pi/extensions/pipe.ts",
    },
  ];
}

function codexAgentDefinition(agent: PipelineSpecAgent): CommandDefinition {
  return {
    content: `${stringifyToml({
      description: agent.description,
      developer_instructions: [
        agent.description,
        "Follow the oisin pipeline phase contract for your assigned role.",
        "Return concrete evidence to the orchestrator.",
      ].join("\n"),
      name: agent.name,
      sandbox_mode:
        agent.role === "test-writer" || agent.role === "code-writer"
          ? "workspace-write"
          : "read-only",
    }).trimEnd()}\n`,
    host: "codex",
    invocation: "$pipe <ticket id or task description>",
    path: `.codex/agents/${agent.name}.toml`,
  };
}

function codexDefinitions(): CommandDefinition[] {
  return [
    {
      content: markdown(
        {
          description:
            "Run the oisin pipeline with Codex subagents. Use when the user asks to run pipe or the oisin pipeline.",
          name: "pipe",
        },
        [
          header("codex").trimEnd(),
          "",
          "Codex does not expose project-defined custom slash commands. Invoke this skill by typing `$pipe <ticket id or task description>` or by selecting it from `/skills`.",
          "",
          renderPipelineWorkflow("<ticket id or task description>"),
          "",
          "Codex execution contract:",
          `- Explicitly spawn subagents for phase work: ${agentNames()}.`,
          "- Keep this skill invocation as the orchestrator that enforces phase order and gates.",
          "",
        ].join("\n")
      ),
      host: "codex",
      invocation: "$pipe <ticket id or task description>",
      path: ".agents/skills/pipe/SKILL.md",
    },
    ...PIPELINE_AGENTS.map(codexAgentDefinition),
  ];
}

function definitionsFor(host: CommandHostSelection): CommandDefinition[] {
  const definitions: Record<CommandHost, () => CommandDefinition[]> = {
    claude: claudeDefinitions,
    codex: codexDefinitions,
    opencode: opencodeDefinitions,
    pi: piDefinitions,
  };
  const hosts = host === "all" ? COMMAND_HOSTS : [host];
  return hosts.flatMap((name) => definitions[name]());
}

function actionFor(
  path: string,
  content: string,
  force: boolean
): InstallAction {
  if (!existsSync(path)) {
    return "create";
  }
  const current = readFileSync(path, "utf8");
  if (current === content) {
    return "unchanged";
  }
  if (
    !(
      current.includes(GENERATED_MARKER) ||
      current.includes(GENERATED_TS_MARKER) ||
      force
    )
  ) {
    return "conflict";
  }
  return "update";
}

export async function installCommands(
  options: InstallCommandsOptions = {}
): Promise<InstallCommandsResult> {
  const cwd = options.cwd ?? process.cwd();
  const host = options.host ?? "all";
  const items: CommandInstallPlanItem[] = [];

  for (const definition of definitionsFor(host)) {
    const target = join(cwd, definition.path);
    const action = actionFor(
      target,
      definition.content,
      Boolean(options.force)
    );
    items.push({
      action,
      host: definition.host,
      invocation: definition.invocation,
      path: definition.path,
    });

    if (options.check || options.dryRun || action === "unchanged") {
      continue;
    }
    if (action === "conflict") {
      continue;
    }

    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, definition.content);
  }

  if (!options.dryRun && items.some((item) => item.action === "conflict")) {
    throw new Error(
      [
        "Refusing to overwrite manually edited command files.",
        ...items
          .filter((item) => item.action === "conflict")
          .map((item) => `- ${item.path}`),
        "Re-run with --force to overwrite them.",
      ].join("\n")
    );
  }

  if (options.check && items.some((item) => item.action !== "unchanged")) {
    throw new Error(
      [
        "Installed command files are not up to date.",
        ...items
          .filter((item) => item.action !== "unchanged")
          .map((item) => `- ${item.path}: ${item.action}`),
      ].join("\n")
    );
  }

  return { items };
}

export function parseCommandHost(
  value: string | undefined
): CommandHostSelection {
  const host = value ?? "all";
  if (host === "all" || COMMAND_HOSTS.includes(host as CommandHost)) {
    return host as CommandHostSelection;
  }
  throw new Error(
    `Unsupported host "${host}". Supported values: all, ${COMMAND_HOSTS.join(", ")}.`
  );
}

export function formatInstallCommandsResult(
  result: InstallCommandsResult
): string {
  return result.items
    .map(
      (item) => `${item.action} ${item.host}: ${item.path} (${item.invocation})`
    )
    .join("\n");
}
