import { existsSync, readFileSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import matter from "gray-matter";
import { stringify as stringifyToml } from "smol-toml";
import { loadPipelineConfig, type PipelineConfig } from "./mastra/config.js";
import { compileWorkflowPlan } from "./workflow-planner.js";

const GENERATED_MARKER = "<!-- Generated by @oisincoveney/pipeline. -->";
const GENERATED_TS_MARKER = "// Generated by @oisincoveney/pipeline.";
const OWNER_MARKER_PREFIX = "<!-- @oisincoveney/pipeline:";
const OWNER_TS_MARKER_PREFIX = "// @oisincoveney/pipeline:";

export const COMMAND_HOSTS = [
  "claude",
  "opencode",
  "codex",
  "kimi",
  "pi",
] as const;

export type CommandHost = (typeof COMMAND_HOSTS)[number];
export type CommandHostSelection = CommandHost | "all";
export type InstallAction = "conflict" | "create" | "unchanged" | "update";

export interface CommandInstallPlanItem {
  action: InstallAction;
  host: CommandHost;
  invocation: string;
  path: string;
}

export interface InstallCommandsOptions {
  check?: boolean;
  cwd?: string;
  dryRun?: boolean;
  force?: boolean;
  host?: CommandHostSelection;
}

export interface InstallCommandsResult {
  items: CommandInstallPlanItem[];
}

interface CommandDefinition {
  content: string;
  host: CommandHost;
  invocation: string;
  path: string;
}

type AgentEntry = [string, PipelineConfig["agents"][string]];

function header(host: CommandHost): string {
  return [GENERATED_MARKER, `${OWNER_MARKER_PREFIX}host=${host} -->`, ""].join(
    "\n"
  );
}

function tsHeader(host: CommandHost): string {
  return [
    GENERATED_TS_MARKER,
    `${OWNER_TS_MARKER_PREFIX}host=${host}`,
    "",
  ].join("\n");
}

function markdown(data: Record<string, unknown>, body: string): string {
  return `${matter.stringify(body.trimEnd(), data).trimEnd()}\n`;
}

function agentEntries(config: PipelineConfig): AgentEntry[] {
  return Object.entries(config.agents).sort(([a], [b]) => a.localeCompare(b));
}

function agentNames(config: PipelineConfig): string {
  return agentEntries(config)
    .map(([name]) => `\`${name}\``)
    .join(", ");
}

function workflowSummary(config: PipelineConfig): string {
  const plan = compileWorkflowPlan(config);
  return [
    `Workflow: ${plan.workflowId}`,
    "",
    ...plan.topologicalOrder.map((node) => {
      const parts = [
        `- ${node.id}`,
        `kind=${node.kind}`,
        node.agent ? `agent=${node.agent}` : "",
        node.needs.length ? `needs=${node.needs.join(",")}` : "needs=none",
      ].filter(Boolean);
      return parts.join(" ");
    }),
  ].join("\n");
}

function grants(agent: PipelineConfig["agents"][string]): string {
  return [
    `tools: ${(agent.tools ?? []).join(", ") || "none"}`,
    `rules: ${(agent.rules ?? []).join(", ") || "none"}`,
    `skills: ${(agent.skills ?? []).join(", ") || "none"}`,
    `mcp_servers: ${(agent.mcp_servers ?? []).join(", ") || "none"}`,
    `filesystem: ${agent.filesystem?.mode ?? "default"}`,
    `network: ${agent.network?.mode ?? "default"}`,
    `output: ${agent.output?.format ?? "text"}`,
  ].join("\n");
}

function claudeTools(agent: PipelineConfig["agents"][string]): string {
  const mapped = new Map([
    ["bash", "Bash"],
    ["edit", "Edit"],
    ["glob", "Glob"],
    ["grep", "Grep"],
    ["list", "LS"],
    ["read", "Read"],
    ["write", "Write"],
  ]);
  return (agent.tools ?? [])
    .flatMap((tool) => {
      const value = mapped.get(tool);
      return value ? [value] : [];
    })
    .join(", ");
}

function claudeDefinitions(config: PipelineConfig): CommandDefinition[] {
  return [
    {
      content: markdown(
        {
          "argument-hint": "<task description>",
          description: "Run the configured pipeline workflow",
        },
        [
          header("claude").trimEnd(),
          "",
          workflowSummary(config),
          "",
          `Delegate work only to configured agents: ${agentNames(config)}.`,
        ].join("\n")
      ),
      host: "claude",
      invocation: "/pipe <task description>",
      path: ".claude/commands/pipe.md",
    },
    ...agentEntries(config).map(([id, agent]) => ({
      content: markdown(
        {
          description: agent.description ?? id,
          name: id,
          tools: claudeTools(agent),
        },
        [
          header("claude").trimEnd(),
          "",
          agent.description ?? id,
          "",
          "Configured grants:",
          grants(agent),
          "",
          instructionsPointer(agent),
        ].join("\n")
      ),
      host: "claude" as const,
      invocation: "/pipe <task description>",
      path: `.claude/agents/${id}.md`,
    })),
  ];
}

function opencodePermission(
  agent: PipelineConfig["agents"][string]
): Record<string, string> {
  const allowed = new Set(agent.tools ?? []);
  return {
    bash: allowed.has("bash") ? "allow" : "deny",
    edit: allowed.has("edit") ? "allow" : "deny",
    glob: allowed.has("glob") ? "allow" : "deny",
    grep: allowed.has("grep") ? "allow" : "deny",
    list: allowed.has("list") ? "allow" : "deny",
    read: allowed.has("read") ? "allow" : "deny",
    task: allowed.has("task") ? "allow" : "deny",
    write: allowed.has("write") ? "allow" : "deny",
  };
}

function opencodeDefinitions(config: PipelineConfig): CommandDefinition[] {
  return [
    {
      content: markdown(
        {
          agent: "pipeline-orchestrator",
          description: "Run the configured pipeline workflow",
          subtask: true,
        },
        [
          header("opencode").trimEnd(),
          "",
          workflowSummary(config),
          "",
          `Delegate work only to configured agents: ${agentNames(config)}.`,
        ].join("\n")
      ),
      host: "opencode",
      invocation: "/pipe <task description>",
      path: ".opencode/commands/pipe.md",
    },
    {
      content: markdown(
        {
          description: "Orchestrate the configured pipeline and enforce gates.",
          mode: "primary",
          permission: {
            bash: "allow",
            edit: "allow",
            glob: "allow",
            grep: "allow",
            list: "allow",
            read: "allow",
            task: "allow",
            write: "allow",
          },
        },
        [
          header("opencode").trimEnd(),
          "",
          "Use the YAML workflow plan as the only source of truth.",
        ].join("\n")
      ),
      host: "opencode",
      invocation: "/pipe <task description>",
      path: ".opencode/agents/pipeline-orchestrator.md",
    },
    ...agentEntries(config).map(([id, agent]) => ({
      content: markdown(
        {
          description: agent.description ?? id,
          mode: "subagent",
          permission: opencodePermission(agent),
        },
        [
          header("opencode").trimEnd(),
          "",
          agent.description ?? id,
          "",
          "Configured grants:",
          grants(agent),
          "",
          instructionsPointer(agent),
        ].join("\n")
      ),
      host: "opencode" as const,
      invocation: "/pipe <task description>",
      path: `.opencode/agents/${id}.md`,
    })),
  ];
}

function codexDefinitions(config: PipelineConfig): CommandDefinition[] {
  return [
    {
      content: markdown(
        {
          description:
            "Run the configured pipeline workflow with Codex subagents.",
          name: "pipe",
        },
        [
          header("codex").trimEnd(),
          "",
          "Invoke this skill with `$pipe <task description>`.",
          "",
          workflowSummary(config),
          "",
          `Use separate configured agents: ${agentNames(config)}.`,
        ].join("\n")
      ),
      host: "codex",
      invocation: "$pipe <task description>",
      path: ".agents/skills/pipe/SKILL.md",
    },
    ...agentEntries(config).map(([id, agent]) => ({
      content: `${stringifyToml({
        description: agent.description ?? id,
        developer_instructions: [
          agent.description ?? id,
          instructionsPointer(agent),
          "Configured grants:",
          grants(agent),
        ].join("\n"),
        name: id,
        sandbox_mode:
          agent.filesystem?.mode === "workspace-write"
            ? "workspace-write"
            : "read-only",
      }).trimEnd()}\n`,
      host: "codex" as const,
      invocation: "$pipe <task description>",
      path: `.codex/agents/${id}.toml`,
    })),
  ];
}

function kimiDefinitions(config: PipelineConfig): CommandDefinition[] {
  return [
    {
      content: markdown(
        {
          description: "Run the configured pipeline workflow with Kimi agents",
        },
        [
          header("kimi").trimEnd(),
          "",
          workflowSummary(config),
          "",
          `Use separate configured agents: ${agentNames(config)}.`,
        ].join("\n")
      ),
      host: "kimi",
      invocation: "/pipe <task description>",
      path: ".kimi/commands/pipe.md",
    },
    ...agentEntries(config).map(([id, agent]) => ({
      content: markdown(
        { description: agent.description ?? id, name: id },
        [
          header("kimi").trimEnd(),
          "",
          agent.description ?? id,
          "",
          "Configured grants:",
          grants(agent),
          "",
          instructionsPointer(agent),
        ].join("\n")
      ),
      host: "kimi" as const,
      invocation: "/pipe <task description>",
      path: `.kimi/agents/${id}.md`,
    })),
  ];
}

function piDefinitions(config: PipelineConfig): CommandDefinition[] {
  return [
    {
      content: markdown(
        {
          "argument-hint": "<task description>",
          description: "Run the configured pipeline workflow with Pi subagents",
        },
        [header("pi").trimEnd(), "", workflowSummary(config)].join("\n")
      ),
      host: "pi",
      invocation: "/pipe <task description>",
      path: ".pi/prompts/pipe.md",
    },
    {
      content: [
        tsHeader("pi").trimEnd(),
        "",
        "interface PiCommand {",
        "  name: string;",
        "}",
        "interface PiCommandContext {",
        "  sendUserMessage(message: string): Promise<void> | void;",
        "  ui: { notify(message: string, type?: string): void };",
        "}",
        "interface PiExtensionApi {",
        "  getCommands?(): PiCommand[];",
        "  registerCommand(",
        "    name: string,",
        "    command: {",
        "      description: string;",
        "      handler(args: string, ctx: PiCommandContext): Promise<void> | void;",
        "    }",
        "  ): void;",
        "}",
        "",
        ...piWorkflowNodesLiteral(config),
        "",
        "function renderSubagentCommand(task: string): string {",
        '  const chain = WORKFLOW_NODES.filter((node) => node.kind === "agent")',
        "    .map((node) => `" +
          "$" +
          "{String(node.agent)}: " +
          "$" +
          "{node.id} " +
          "$" +
          "{task}" +
          "`)",
        '    .join(" -> ");',
        ["  return `/chain ", "$", "{JSON.stringify(chain)}`;"].join(""),
        "}",
        "",
        "export default function pipelineWorkNext(pi: PiExtensionApi): void {",
        '  pi.registerCommand("pipe", {',
        '    description: "Run the configured pipeline with Pi subagents",',
        "    handler: async (args: string, ctx) => {",
        '      const task = String(args ?? "").trim();',
        "      if (!task) {",
        '        ctx.ui.notify("Usage: /pipe <task description>", "error");',
        "        return;",
        "      }",
        "      const commands =",
        '        typeof pi.getCommands === "function" ? pi.getCommands() : [];',
        "      const hasPiSubagents = commands.some((command) =>",
        '        ["run", "chain", "parallel", "run-chain", "subagents-doctor"].some(',
        "          (name) => command.name === name || command.name.startsWith(`" +
          "$" +
          "{name}:" +
          "`)",
        "        )",
        "      );",
        "      if (!hasPiSubagents) {",
        '        ctx.ui.notify("Install pi-subagents before running /pipe.", "error");',
        "        return;",
        "      }",
        "      await ctx.sendUserMessage(renderSubagentCommand(task));",
        "    },",
        "  });",
        "}",
        "",
      ].join("\n"),
      host: "pi",
      invocation: "/pipe <task description>",
      path: ".pi/extensions/pipe.ts",
    },
  ];
}

function piWorkflowNodesLiteral(config: PipelineConfig): string[] {
  const plan = compileWorkflowPlan(config);
  return [
    "const WORKFLOW_NODES = [",
    ...plan.topologicalOrder.flatMap((node) => [
      "  {",
      `    agent: ${JSON.stringify(node.agent ?? null)},`,
      `    id: ${JSON.stringify(node.id)},`,
      `    kind: ${JSON.stringify(node.kind)},`,
      `    needs: ${JSON.stringify(node.needs)},`,
      "  },",
    ]),
    "] as const;",
  ];
}

function instructionsPointer(agent: PipelineConfig["agents"][string]): string {
  if (agent.instructions.path) {
    return `Instructions: ${agent.instructions.path}`;
  }
  return `Instructions:\n${agent.instructions.inline ?? ""}`;
}

function definitionsFor(
  host: CommandHostSelection,
  config: PipelineConfig
): CommandDefinition[] {
  const definitions: Record<CommandHost, () => CommandDefinition[]> = {
    claude: () => claudeDefinitions(config),
    codex: () => codexDefinitions(config),
    kimi: () => kimiDefinitions(config),
    opencode: () => opencodeDefinitions(config),
    pi: () => piDefinitions(config),
  };
  const hosts = host === "all" ? COMMAND_HOSTS : [host];
  return hosts.flatMap((name) => definitions[name]());
}

function actionFor(
  path: string,
  content: string,
  force: boolean
): InstallAction {
  if (!existsSync(path)) {
    return "create";
  }
  const current = readFileSync(path, "utf8");
  if (current === content) {
    return "unchanged";
  }
  if (
    !(
      current.includes(GENERATED_MARKER) ||
      current.includes(GENERATED_TS_MARKER) ||
      force
    )
  ) {
    return "conflict";
  }
  return "update";
}

export async function installCommands(
  options: InstallCommandsOptions = {}
): Promise<InstallCommandsResult> {
  const cwd = options.cwd ?? process.cwd();
  const host = options.host ?? "all";
  const config = loadPipelineConfig(cwd);
  const items: CommandInstallPlanItem[] = [];

  for (const definition of definitionsFor(host, config)) {
    const target = join(cwd, definition.path);
    const action = actionFor(
      target,
      definition.content,
      Boolean(options.force)
    );
    items.push({
      action,
      host: definition.host,
      invocation: definition.invocation,
      path: definition.path,
    });

    if (options.check || options.dryRun || action === "unchanged") {
      continue;
    }
    if (action === "conflict") {
      continue;
    }

    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, definition.content);
  }

  if (!options.dryRun && items.some((item) => item.action === "conflict")) {
    throw new Error(
      [
        "Refusing to overwrite manually edited command files.",
        ...items
          .filter((item) => item.action === "conflict")
          .map((item) => `- ${item.path}`),
        "Re-run with --force to overwrite them.",
      ].join("\n")
    );
  }

  if (options.check && items.some((item) => item.action !== "unchanged")) {
    throw new Error(
      [
        "Installed command files are not up to date.",
        ...items
          .filter((item) => item.action !== "unchanged")
          .map((item) => `- ${item.path}: ${item.action}`),
      ].join("\n")
    );
  }

  return { items };
}

export function parseCommandHost(
  value: string | undefined
): CommandHostSelection {
  const host = value ?? "all";
  if (host === "all" || COMMAND_HOSTS.includes(host as CommandHost)) {
    return host as CommandHostSelection;
  }
  throw new Error(
    `Unsupported host "${host}". Supported values: all, ${COMMAND_HOSTS.join(", ")}.`
  );
}

export function formatInstallCommandsResult(
  result: InstallCommandsResult
): string {
  return result.items
    .map(
      (item) => `${item.action} ${item.host}: ${item.path} (${item.invocation})`
    )
    .join("\n");
}
